name: .NET

on: [push]

jobs:
  Despliegue:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
    - name: instalación de .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restauran dependencias 
      run: dotnet restore

    - name: Compilado
      run: dotnet build --no-restore

    - name: Pruebas
      run: dotnet test --no-build --verbosity normal

    
    - uses: actions/checkout@v4    
    - name: Despliegue al servidor AWS
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}

    - name: Ejecución cmd en AWS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/
          sudo dotnet build